### PR TITLE
start creating ui for commits, thottle commit array

### PR DESCRIPTION
**Pull request by gemfarmer**
I started creating a ui for the angular, also started using some lodash functions to throttle the commit array so that it only contains unique commits.

### CODE REVIEW

**Comment by gemfarmer** [comment]
@mjhea0 pull in when you get a chance

**Comment by mjhea0** [comment]
@gemfarmer you have keys in the _config.js file

**Comment by mjhea0** [comment]
@gemfarmer merge conflict https://github.com/RefactorU/hackathon-live-feed/pull/87/files#diff-ea75b530d74f94670cea053feb8b961bR126

**Comment by mjhea0** [comment]
@gemfarmer after you clean those up, I'll merge - thanks!

**Comment by gemfarmer** [comment]
@mjhea0

**Comment by gemfarmer** [comment]
see new pull request "ui-tuning"

https://github.com/RefactorU/hackathon-live-feed/pull/88

**Pull request closed without merging**
